version: '3.3'
services:
  app:  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./:/app

  nginx:
    restart: always
    build:
      context: ./nginx/default.conf
      dockerfile: ./nginx/dockerfile
    ports:
      - 80:80